version: '3.8'

services:
  nextjs:
    # Development-specific overrides
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Better file watching in Docker
      # Playwright configuration for headless browser testing
      - PLAYWRIGHT_BROWSERS_PATH=/app/.playwright
      - DISPLAY=:99 # Virtual display for headless browsers
    volumes:
      # Additional development volumes
      - ./logs:/app/logs
      - ./coverage:/app/coverage
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      # Cache Playwright browsers to avoid re-downloading
      - playwright_browsers:/app/.playwright
    # Development-specific labels
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextjs.rule=Host(`localhost`)'
      - 'traefik.http.routers.nextjs.entrypoints=web'
      - 'traefik.http.services.nextjs.loadbalancer.server.port=3000'

  docs:
    # Development-specific overrides for docs service
    # environment:
    # Jekyll environment removed - now using Docusaurus
    # Development-specific labels
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.docs.rule=Host(`docs.localhost`)'
      - 'traefik.http.routers.docs.entrypoints=web'
      - 'traefik.http.services.docs.loadbalancer.server.port=4000'

volumes:
  playwright_browsers:
    driver: local
