packages:
  - '.'

strictDepBuilds: false
dangerouslyAllowAllBuilds: true

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@scarf/scarf': set this to true or false
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false

overrides:
  tough-cookie@<4.1.3: '>=4.1.3'
  braces@<3.0.3: '>=3.0.3'
  undici: '7.28.0'
  serialize-javascript: '7.0.3'

minimumReleaseAgeExclude:
  - js-yaml@5.0.0
