/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated sidebar from the filesystem
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the root of src/
    },
  ],

  // You can also create manual sidebars for specific sections:
  // apiSidebar: [
  //   {
  //     type: 'category',
  //     label: 'API Documentation',
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'app/api', // Generate from src/app/api/
  //       },
  //     ],
  //   },
  // ],
};

module.exports = sidebars; 