-- Migration: Add missing columns with basic PostgreSQL syntax
-- Description: Simple ALTER TABLE statements to add missing columns
-- Author: System Wizard 🧙‍♂️
-- Date: 2025-01-27

-- Add missing columns to permissions table
ALTER TABLE PERMISSIONS
    ADD COLUMN RISK_LEVEL VARCHAR(
        20
    ) DEFAULT 'low';

ALTER TABLE PERMISSIONS
    ADD COLUMN SORT_ORDER INTEGER DEFAULT 0;

ALTER TABLE PERMISSIONS
    ADD COLUMN IS_ARCHIVED BOOLEAN DEFAULT FALSE;

ALTER TABLE PERMISSIONS
    ADD COLUMN ARCHIVED_AT TIMESTAMP;

ALTER TABLE PERMISSIONS
    ADD COLUMN ARCHIVED_BY INTEGER;

ALTER TABLE PERMISSIONS
    ADD COLUMN ARCHIVE_REASON TEXT;

ALTER TABLE PERMISSIONS
    ADD COLUMN METADATA JSONB DEFAULT '{}';

ALTER TABLE PERMISSIONS
    ADD COLUMN DEPENDENCIES TEXT[] DEFAULT '{}';

ALTER TABLE PERMISSIONS
    ADD COLUMN IS_ACTIVE BOOLEAN DEFAULT TRUE;

-- Add missing columns to user_roles table
ALTER TABLE USER_ROLES
    ADD COLUMN SORT_ORDER INTEGER DEFAULT 0;

ALTER TABLE USER_ROLES
    ADD COLUMN IS_ARCHIVED BOOLEAN DEFAULT FALSE;

ALTER TABLE USER_ROLES
    ADD COLUMN ARCHIVED_AT TIMESTAMP;

ALTER TABLE USER_ROLES
    ADD COLUMN ARCHIVED_BY INTEGER;

ALTER TABLE USER_ROLES
    ADD COLUMN ARCHIVE_REASON TEXT;

ALTER TABLE USER_ROLES
    ADD COLUMN METADATA JSONB DEFAULT '{}';

ALTER TABLE USER_ROLES
    ADD COLUMN ROLE_COLOR VARCHAR(
        7
    ) DEFAULT '#6366F1';

ALTER TABLE USER_ROLES
    ADD COLUMN ROLE_ICON VARCHAR(
        50
    ) DEFAULT 'user';

ALTER TABLE USER_ROLES
    ADD COLUMN IS_ACTIVE BOOLEAN DEFAULT TRUE;

-- Set default values for existing data
UPDATE PERMISSIONS
SET
    RISK_LEVEL = 'low'
WHERE
    RISK_LEVEL IS NULL;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 1
WHERE
    CATEGORY = 'admin'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 2
WHERE
    CATEGORY = 'moderation'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 3
WHERE
    CATEGORY = 'content'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 4
WHERE
    CATEGORY = 'community'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 5
WHERE
    CATEGORY = 'emoji'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 6
WHERE
    CATEGORY = 'subscription'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 7
WHERE
    CATEGORY = 'beta'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 8
WHERE
    CATEGORY = 'vip'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 9
WHERE
    CATEGORY = 'review'
    AND SORT_ORDER = 0;

UPDATE PERMISSIONS
SET
    SORT_ORDER = 10
WHERE
    SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 1
WHERE
    NAME = 'admin'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 2
WHERE
    NAME = 'moderator'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 3
WHERE
    NAME = 'content_reviewer'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 4
WHERE
    NAME = 'community_manager'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 5
WHERE
    NAME = 'content_creator'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 6
WHERE
    NAME = 'vip_user'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 7
WHERE
    NAME = 'beta_tester'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 8
WHERE
    NAME = 'basic'
    AND SORT_ORDER = 0;

UPDATE USER_ROLES
SET
    SORT_ORDER = 9
WHERE
    SORT_ORDER = 0;

-- Simple verification
SELECT
    'Migration completed successfully' AS STATUS;