-- Migration: Add sample analytics data for testing
-- Description: Adds sample data to analytics tables for testing the dashboard
-- Author: System Wizard 🧙‍♂️
-- Date: 2025-01-13

-- ================================
-- SAMPLE ANALYTICS DATA
-- ================================

-- Insert sample sessions
INSERT INTO ANALYTICS_SESSIONS (
    ID,
    SESSION_ID,
    USER_ID,
    SESSION_START_AT,
    SESSION_END_AT,
    TOTAL_SESSION_DURATION_SECONDS,
    TOTAL_PAGE_VIEWS,
    TOTAL_CLICKS,
    IS_BOUNCE,
    DEVICE_TYPE,
    BROWSER_NAME,
    BROWSER_VERSION,
    OS_NAME,
    OS_VERSION,
    COUNTRY_CODE,
    COUNTRY_NAME,
    CITY_NAME,
    REGION_NAME,
    LATITUDE,
    LONGITUDE,
    IS_VPN,
    IS_PROXY,
    IS_TOR,
    VPN_PROVIDER,
    UTM_SOURCE,
    UTM_MEDIUM,
    UTM_CAMPAIGN,
    UTM_CONTENT,
    UTM_TERM,
    REFERRER_URL,
    ENTRY_PAGE,
    EXIT_PAGE,
    DEVICE_FINGERPRINT,
    CREATED_AT,
    UPDATED_AT
) VALUES
 -- Sample session 1 (US, Chrome, Desktop)
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour',
    3600,
    5,
    12,
    FALSE,
    'Desktop',
    'Chrome',
    '120.0',
    'Windows',
    '11',
    'US',
    'United States',
    'New York',
    'New York',
    40.7128,
    -74.0060,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    'google',
    'organic',
    NULL,
    NULL,
    NULL,
    'https://google.com',
    '/home',
    '/pricing',
    'fp_desktop_001',
    NOW(),
    NOW()
),
 
-- Sample session 2 (UK, Firefox, Mobile)
(
    GEN_RANDOM_UUID(),
    'sess_002',
    2,
    NOW() - INTERVAL '4 hours',
    NOW() - INTERVAL '3 hours',
    3000,
    3,
    8,
    FALSE,
    'Mobile',
    'Firefox',
    '121.0',
    'Android',
    '13',
    'GB',
    'United Kingdom',
    'London',
    'England',
    51.5074,
    -0.1278,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    'direct',
    'none',
    NULL,
    NULL,
    NULL,
    NULL,
    '/gallery',
    '/posts',
    'fp_mobile_001',
    NOW(),
    NOW()
),
 
-- Sample session 3 (Germany, Safari, Tablet, VPN)
(
    GEN_RANDOM_UUID(),
    'sess_003',
    3,
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '5 hours',
    2400,
    4,
    10,
    FALSE,
    'Tablet',
    'Safari',
    '17.0',
    'iOS',
    '17.1',
    'DE',
    'Germany',
    'Berlin',
    'Berlin',
    52.5200,
    13.4050,
    TRUE,
    FALSE,
    FALSE,
    'NordVPN',
    'facebook',
    'social',
    'spring_sale',
    NULL,
    NULL,
    'https://facebook.com',
    '/home',
    '/admin',
    'fp_tablet_001',
    NOW(),
    NOW()
),
 
-- Sample session 4 (Canada, Edge, Desktop)
(
    GEN_RANDOM_UUID(),
    'sess_004',
    4,
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '7 hours',
    1800,
    2,
    5,
    FALSE,
    'Desktop',
    'Edge',
    '119.0',
    'Windows',
    '10',
    'CA',
    'Canada',
    'Toronto',
    'Ontario',
    43.6532,
    -79.3832,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    'twitter',
    'social',
    NULL,
    NULL,
    NULL,
    'https://twitter.com',
    '/posts',
    '/posts',
    'fp_desktop_002',
    NOW(),
    NOW()
),
 
-- Sample session 5 (France, Chrome, Mobile, Proxy)
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    NOW() - INTERVAL '10 hours',
    NOW() - INTERVAL '9 hours',
    4200,
    6,
    15,
    FALSE,
    'Mobile',
    'Chrome',
    '120.0',
    'Android',
    '14',
    'FR',
    'France',
    'Paris',
    'Île-de-France',
    48.8566,
    2.3522,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    'email',
    'newsletter',
    'weekly_digest',
    NULL,
    NULL,
    'https://idling.app',
    '/home',
    '/pricing',
    'fp_mobile_002',
    NOW(),
    NOW()
);

-- Insert sample page views
INSERT INTO ANALYTICS_PAGE_VIEWS (
    ID,
    SESSION_ID,
    PAGE_PATH,
    PAGE_TITLE,
    OCCURRED_AT,
    LOAD_TIME_MS,
    TIME_TO_FIRST_BYTE_MS,
    FIRST_CONTENTFUL_PAINT_MS,
    LARGEST_CONTENTFUL_PAINT_MS,
    CUMULATIVE_LAYOUT_SHIFT,
    TIME_ON_PAGE_SECONDS,
    SCROLL_DEPTH_PERCENTAGE,
    EXIT_PAGE,
    BOUNCE,
    REFERRER_URL,
    CREATED_AT
) VALUES
 -- Session 1 page views
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/home',
    'Home - Idling.app',
    NOW() - INTERVAL '2 hours',
    1200,
    300,
    800,
    1100,
    0.05,
    120,
    75,
    FALSE,
    FALSE,
    'https://google.com',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/gallery',
    'Gallery - Idling.app',
    NOW() - INTERVAL '110 minutes',
    800,
    200,
    500,
    750,
    0.02,
    180,
    90,
    FALSE,
    FALSE,
    '/home',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/posts',
    'Posts - Idling.app',
    NOW() - INTERVAL '90 minutes',
    950,
    250,
    600,
    900,
    0.03,
    200,
    85,
    FALSE,
    FALSE,
    '/gallery',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/pricing',
    'Pricing - Idling.app',
    NOW() - INTERVAL '70 minutes',
    1100,
    280,
    700,
    1000,
    0.04,
    240,
    95,
    TRUE,
    FALSE,
    '/posts',
    NOW()
),
 
-- Session 2 page views
(
    GEN_RANDOM_UUID(),
    'sess_002',
    '/gallery',
    'Gallery - Idling.app',
    NOW() - INTERVAL '4 hours',
    1400,
    350,
    900,
    1200,
    0.06,
    150,
    60,
    FALSE,
    FALSE,
    NULL,
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_002',
    '/posts',
    'Posts - Idling.app',
    NOW() - INTERVAL '3.5 hours',
    1000,
    250,
    650,
    950,
    0.03,
    170,
    80,
    TRUE,
    FALSE,
    '/gallery',
    NOW()
),
 
-- Session 3 page views
(
    GEN_RANDOM_UUID(),
    'sess_003',
    '/home',
    'Home - Idling.app',
    NOW() - INTERVAL '6 hours',
    900,
    200,
    550,
    800,
    0.02,
    100,
    70,
    FALSE,
    FALSE,
    'https://facebook.com',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_003',
    '/admin',
    'Admin Dashboard - Idling.app',
    NOW() - INTERVAL '5.5 hours',
    1300,
    320,
    800,
    1150,
    0.04,
    300,
    100,
    TRUE,
    FALSE,
    '/home',
    NOW()
);

-- Insert sample clicks
INSERT INTO ANALYTICS_CLICKS (
    ID,
    SESSION_ID,
    PAGE_PATH,
    CLICK_X,
    CLICK_Y,
    ELEMENT_SELECTOR,
    ELEMENT_TEXT,
    ELEMENT_TYPE,
    CLICK_TYPE,
    OCCURRED_AT,
    CREATED_AT
) VALUES
 -- Session 1 clicks
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/home',
    150,
    200,
    'nav .logo',
    'Idling.app',
    'link',
    'click',
    NOW() - INTERVAL '2 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/home',
    300,
    400,
    '.hero-button',
    'Get Started',
    'button',
    'click',
    NOW() - INTERVAL '115 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/gallery',
    250,
    300,
    '.image-grid .image:nth-child(3)',
    '',
    'image',
    'click',
    NOW() - INTERVAL '105 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/posts',
    200,
    150,
    '.post-card h3',
    'Latest Updates',
    'heading',
    'click',
    NOW() - INTERVAL '85 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    '/pricing',
    400,
    500,
    '.pricing-card.premium .subscribe-btn',
    'Subscribe Now',
    'button',
    'click',
    NOW() - INTERVAL '65 minutes',
    NOW()
),
 
-- Session 2 clicks
(
    GEN_RANDOM_UUID(),
    'sess_002',
    '/gallery',
    180,
    250,
    '.filter-buttons .filter-btn',
    'Recent',
    'button',
    'click',
    NOW() - INTERVAL '3.8 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_002',
    '/gallery',
    320,
    400,
    '.image-grid .image:nth-child(5)',
    '',
    'image',
    'click',
    NOW() - INTERVAL '3.6 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_002',
    '/posts',
    220,
    180,
    '.post-card .read-more',
    'Read More',
    'link',
    'click',
    NOW() - INTERVAL '3.4 hours',
    NOW()
),
 
-- Session 3 clicks
(
    GEN_RANDOM_UUID(),
    'sess_003',
    '/home',
    280,
    350,
    '.hero-section .cta-button',
    'Learn More',
    'button',
    'click',
    NOW() - INTERVAL '5.8 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_003',
    '/admin',
    100,
    100,
    '.admin-nav .tab[data-tab="subscriptions"]',
    'Subscriptions',
    'button',
    'click',
    NOW() - INTERVAL '5.4 hours',
    NOW()
);

-- Insert sample subscription events
INSERT INTO ANALYTICS_SUBSCRIPTION_EVENTS (
    ID,
    SESSION_ID,
    USER_ID,
    EVENT_TYPE,
    PLAN_NAME,
    PLAN_PRICE,
    EVENT_VALUE,
    FUNNEL_STEP,
    FUNNEL_POSITION,
    PAYMENT_METHOD,
    OCCURRED_AT,
    CREATED_AT
) VALUES
 -- Subscription funnel events
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'subscription_view',
    'Premium',
    9.99,
    NULL,
    'Landing',
    1,
    NULL,
    NOW() - INTERVAL '2 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'pricing_view',
    'Premium',
    9.99,
    NULL,
    'Pricing',
    2,
    NULL,
    NOW() - INTERVAL '70 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'payment_attempt',
    'Premium',
    9.99,
    NULL,
    'Payment',
    3,
    'credit_card',
    NOW() - INTERVAL '65 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'payment_success',
    'Premium',
    9.99,
    9.99,
    'Success',
    4,
    'credit_card',
    NOW() - INTERVAL '60 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_003',
    3,
    'subscription_view',
    'Basic',
    4.99,
    NULL,
    'Landing',
    1,
    NULL,
    NOW() - INTERVAL '6 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_003',
    3,
    'pricing_view',
    'Basic',
    4.99,
    NULL,
    'Pricing',
    2,
    NULL,
    NOW() - INTERVAL '5.5 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    'subscription_view',
    'Pro',
    19.99,
    NULL,
    'Landing',
    1,
    NULL,
    NOW() - INTERVAL '10 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    'pricing_view',
    'Pro',
    19.99,
    NULL,
    'Pricing',
    2,
    NULL,
    NOW() - INTERVAL '9.5 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    'payment_attempt',
    'Pro',
    19.99,
    NULL,
    'Payment',
    3,
    'paypal',
    NOW() - INTERVAL '9.2 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    'payment_success',
    'Pro',
    19.99,
    19.99,
    'Success',
    4,
    'paypal',
    NOW() - INTERVAL '9 hours',
    NOW()
);

-- Insert sample user behavior events
INSERT INTO ANALYTICS_USER_BEHAVIOR (
    ID,
    SESSION_ID,
    USER_ID,
    EVENT_TYPE,
    EVENT_DATA,
    OCCURRED_AT,
    CREATED_AT
) VALUES (
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'scroll_depth',
    '{"percentage": 75, "page": "/home"}',
    NOW() - INTERVAL '2 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_001',
    1,
    'form_interaction',
    '{"form": "newsletter", "action": "focus"}',
    NOW() - INTERVAL '110 minutes',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_002',
    2,
    'scroll_depth',
    '{"percentage": 90, "page": "/gallery"}',
    NOW() - INTERVAL '3.8 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_003',
    3,
    'page_visibility',
    '{"visibility": "hidden", "duration": 120}',
    NOW() - INTERVAL '5.6 hours',
    NOW()
),
(
    GEN_RANDOM_UUID(),
    'sess_005',
    5,
    'scroll_depth',
    '{"percentage": 95, "page": "/pricing"}',
    NOW() - INTERVAL '9.5 hours',
    NOW()
);

-- ================================
-- VERIFICATION QUERY
-- ================================
-- Uncomment to verify the sample data was inserted correctly:
-- SELECT
--     (SELECT COUNT(*) FROM analytics_sessions) as sessions_count,
--     (SELECT COUNT(*) FROM analytics_page_views) as page_views_count,
--     (SELECT COUNT(*) FROM analytics_clicks) as clicks_count,
--     (SELECT COUNT(*) FROM analytics_subscription_events) as subscription_events_count,
--     (SELECT COUNT(*) FROM analytics_user_behavior) as user_behavior_count;