# Jekyll Configuration for GitHub Pages
title: "Idling.app Documentation"
description: "Complete documentation for the Idling.app project - migrations, deployment, development guides and more"
url: "https://underwood-inc.github.io"
baseurl: "/idling.app__UI"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings for better markdown processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Plugins (GitHub Pages whitelisted)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Collections for co-located documentation - no physical directories needed
# Jekyll will find files via plugins, not directory scanning
collections: {}

# Defaults for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Search configuration - co-located docs found via plugins
search:
  enabled: true
  exclude_files:
    - "*.json"
    - "*.xml"
    - "*.txt"
  include_content: true
  content_length: 2000

# Documentation paths for co-located docs - actual file locations in codebase
documentation_paths:
  components: "../src/components"
  libraries: "../src/lib"
  api: "../src/app/api"
  templates: "../src/templates"
  community: "../community"
  diagrams: "./diagrams"

# Auto-generated navigation from frontmatter
# The DynamicNavigationGenerator plugin will create site.data.auto_navigation
# No manual configuration needed - just add frontmatter to your markdown files!

# Exclude files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages
  - coverage-artifacts

# SEO
author: "Underwood Inc"
twitter:
  username: "idling_app"
social:
  name: "Idling.app"
  links:
    - "https://github.com/Underwood-Inc/idling.app__UI"

# Analytics (optional)
google_analytics: # Add GA tracking ID if needed

# GitHub Pages settings
repository: "Underwood-Inc/idling.app__UI"
github:
  repository_url: "https://github.com/Underwood-Inc/idling.app__UI" 