# Development configuration overrides
# This file is used to override settings for local development
# Usage: bundle exec jekyll serve --config _config.yml,_config_dev.yml

baseurl: ""
url: "http://localhost:4000"

# Development-specific Jekyll configuration
# This file overrides settings in _config.yml for local development

# Disable problematic plugins for local development
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  # jekyll-github-metadata disabled for local development

# Custom plugins (loaded from _plugins directory)
plugins_dir: _plugins
safe: false  # Allow custom plugins to run

# Explicitly disable GitHub metadata plugin
github-metadata:
  enabled: false

# Local development settings
host: 0.0.0.0
port: 4000
incremental: true

# Disable GitHub-specific features for local dev
repository: ""
github: {}

# Set environment variables for local development
jekyll_env: development

# Disable GitHub Pages specific features
github_pages_env: false

# Show drafts and future posts in development
show_drafts: true
future: true

# Development-specific excludes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gem"
  - "*.gemspec"
  - tools/
  - README.md
  - LICENSE
  - CNAME 