openapi: 3.0.0
paths:
  /api/admin/roles:
    get:
      summary: Get available roles for assignment
      description: Retrieve a list of available roles that can be assigned to users. Excludes protected roles that can only be assigned via database.
      tags:
        - Admin
      security:
        - NextAuth: []
      responses:
        200:
          description: Successfully retrieved available roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: Role ID
                    name:
                      type: string
                      description: Role name
                    display_name:
                      type: string
                      description: Human-readable role name
                    description:
                      type: string
                      nullable: true
                      description: Role description
                  required: [id, name, display_name]
        401:
          description: Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
        403:
          description: Insufficient permissions - requires ADMIN.USERS_MANAGE permission
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Insufficient permissions"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to fetch roles" 