# Site settings
title: "Rate Limiting & Security Documentation"
description: "Comprehensive guide to our application's rate limiting and security features"
baseurl: "/docs"
url: "https://your-domain.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - overview.md
  - how-it-works.md
  - user-guide.md
  - troubleshooting.md
  - admin-guide.md

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true 