name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd repos/idling.app__UI/
            git checkout -- .
            git reset --hard
            git clean -fd
            git checkout master
            git pull origin master
            corepack enable
            corepack install
            pnpm install
            pnpm build
            pm2 restart 0
