name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: prep ssh
        run: sudo apt-get install sshpass

      - name: SSH and deploy
        run: |
          sshpass -p '${{ secrets.SSH_PASS }}'' ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
