name: Quality Assurance

# Concurrency group to cancel in-progress runs on PR updates
concurrency:
  group: tests-pr-${{ github.event.pull_request.number || github.ref }}-${{ github.sha }}
  cancel-in-progress: true

# PERFORMANCE OPTIMIZATION:
# This workflow uses a shared setup job to install dependencies and browsers once,
# then caches them for reuse across all matrix jobs. This significantly reduces
# build time and resource usage compared to each matrix job installing dependencies separately.

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'docs/**'

# Required permissions for GitHub Actions
permissions:
  contents: read
  actions: write
  checks: write
  pull-requests: write

# Environment variables available to all jobs
env:
  AUTH_TRUST_HOST: true
  NEXTAUTH_URL: http://localhost:3000
  # Secrets are encrypted environment variables
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  AUTHJS_SESSION_TOKEN: ${{ secrets.AUTHJS_SESSION_TOKEN }}
  AUTHJS_CALLBACK_URL: ${{ secrets.AUTHJS_CALLBACK_URL }}
  AUTHJS_CSRF_TOKEN: ${{ secrets.AUTHJS_CSRF_TOKEN }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST_AUTH_METHOD: md5
  POSTGRES_INITDB_ARGS: --auth-host=md5
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  setup:
    timeout-minutes: 10
    name: Setup Environment
    runs-on: ubuntu-latest
    environment: actions
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
      node-version: ${{ steps.node-version.outputs.version }}
    steps:
      # Checkout code with full git history for proper versioning
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js using LTS version and output version for reuse
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: lts/*
          cache: 'yarn' # Enable built-in yarn caching

      # Output Node.js version for other jobs
      - name: Get Node.js version
        id: node-version
        run: echo "version=$(node --version)" >> $GITHUB_OUTPUT

      # Install project dependencies
      - name: Install dependencies
        run: npm install -g yarn && yarn install --check-files

      # Install Playwright browsers for caching
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Cache dependencies and browsers to speed up future runs
      - name: Cache dependencies and browsers
        id: cache
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            ~/.cache/playwright
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-deps-browsers-${{ hashFiles('**/yarn.lock', '**/package.json') }}

  playwright-tests:
    name: Playwright Tests
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: actions
    continue-on-error: true # Make Playwright tests optional - don't fail the workflow
    strategy:
      fail-fast: false # Continue with other shards if one fails
      matrix:
        shard: [1, 2, 3] # Run tests in 3 parallel shards
    services:
      # PostgreSQL service container for E2E tests
      postgres:
        image: postgres
        env:
          # Database configuration
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: md5
          POSTGRES_INITDB_ARGS: --auth-host=md5
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      # Use the same Node.js version as setup job
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      # Restore cached dependencies and browsers from setup job
      - name: Restore dependencies and browsers cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.cache/playwright
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-deps-browsers-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-browsers-
            ${{ runner.os }}-deps-
          fail-on-cache-miss: false

      # Install dependencies if cache miss (first run or cache eviction)
      - name: Install dependencies and browsers
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          yarn install --check-files
          npx playwright install --with-deps

      # Setup test database
      - name: Run migrations
        run: psql -v POSTGRES_DB="$POSTGRES_DB" -v POSTGRES_PASSWORD="$POSTGRES_PASSWORD" -v POSTGRES_USER="$POSTGRES_USER" -f ./src/lib/scripts/000-init.sql postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@${{secrets.POSTGRES_HOST}}:${{secrets.POSTGRES_PORT}}

      # Run E2E tests with sharding
      - name: Run Playwright tests (Shard ${{ matrix.shard }}/3)
        run: |
          echo "::group::Running Playwright Tests (Shard ${{ matrix.shard }}/3)"
          # Create directories for each project
          mkdir -p test-results/{chromium,firefox,webkit} playwright-report

          # Run tests with reporters configured in playwright.config.ts
          IS_CI=1 FORCE_COLOR=1 yarn playwright test \
            --shard=${{ matrix.shard }}/3

          # Debug: Show test results
          echo "Test results directory contents:"
          ls -la test-results/
          echo "\nTest results by project:"
          for dir in test-results/*/; do
            echo "\n$dir:"
            ls -la "$dir"
          done
          echo "::endgroup::"

      # Upload test results for this shard
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.shard }}
          path: |
            test-results/**/*
            playwright-report/**/*
          retention-days: 30

      # Upload traces only on failure
      - name: Upload test traces on failure
        if: ${{ failure() && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ matrix.shard }}
          path: test-results/
          retention-days: 7

  jest-tests:
    timeout-minutes: 15
    name: Jest Tests
    needs: setup
    runs-on: ubuntu-latest
    environment: actions
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3] # Run tests in 3 parallel shards
    steps:
      - uses: actions/checkout@v4

      # Use the same Node.js version as setup job
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      # Restore cached dependencies from setup job
      - name: Restore dependencies cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.cache/playwright
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-deps-browsers-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-browsers-
            ${{ runner.os }}-deps-
          fail-on-cache-miss: false

      # Install dependencies if cache miss (first run or cache eviction)
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn install --check-files

      # Run unit tests with sharding
      - name: Run Jest tests (Shard ${{ matrix.shard }}/3)
        run: |
          echo "::group::Running Jest Tests (Shard ${{ matrix.shard }}/3)"
          FORCE_COLOR=1 yarn test:coverage --ci --colors --json --shard=${{ matrix.shard }}/3 --testLocationInResults --outputFile="$GITHUB_WORKSPACE/jest-results-${{ matrix.shard }}.json"
          echo "::endgroup::"

      # Upload coverage reports for each shard
      - name: Upload Jest coverage
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-${{ matrix.shard }}
          path: coverage/
          retention-days: 30

  # Documentation coverage job integrated into test suite
  documentation-coverage:
    timeout-minutes: 10
    name: Documentation Coverage
    needs: setup
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use the same Node.js version as setup job
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      # Restore cached dependencies from setup job
      - name: Restore dependencies cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.cache/playwright
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-deps-browsers-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-browsers-
            ${{ runner.os }}-deps-
          fail-on-cache-miss: false

      # Install dependencies if cache miss
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn install --check-files

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies
        run: |
          pip install interrogate pydocstyle

      - name: 🐍 Check Python docstring coverage
        id: interrogate
        run: |
          # Run interrogate and capture output
          if interrogate --fail-under=85 --verbose=2 src/ > interrogate_output.txt 2>&1; then
            echo "interrogate_passed=true" >> $GITHUB_OUTPUT
          else
            echo "interrogate_passed=false" >> $GITHUB_OUTPUT
          fi

          # Extract docstring coverage percentage
          DOCSTRING_COVERAGE=$(grep -oP 'TOTAL.*?(\K\d+(?=\.\d+%))' interrogate_output.txt || echo "0")
          echo "docstring_coverage=${DOCSTRING_COVERAGE}" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: 📚 Check documentation files coverage
        id: docs-coverage
        run: |
          # Comprehensive documentation coverage check
          total_files=0
          documented_files=0

          # Check ALL TypeScript/JavaScript files in src/
          for file in $(find src/ -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" 2>/dev/null || true); do
            if [ -f "$file" ]; then
              total_files=$((total_files + 1))
              
              # Convert src/path/file.ts to DOCS/src/path/file.md
              doc_file="DOCS/${file%.*}.md"
              
              if [ -f "$doc_file" ]; then
                documented_files=$((documented_files + 1))
              fi
            fi
          done

          # Calculate coverage
          if [ $total_files -eq 0 ]; then
            DOC_COVERAGE=100
          else
            DOC_COVERAGE=$((documented_files * 100 / total_files))
          fi

          echo "doc_coverage=${DOC_COVERAGE}" >> $GITHUB_OUTPUT
          echo "total_files=${total_files}" >> $GITHUB_OUTPUT
          echo "documented_files=${documented_files}" >> $GITHUB_OUTPUT

          if [ $DOC_COVERAGE -ge 85 ]; then
            echo "docs_coverage_passed=true" >> $GITHUB_OUTPUT
          else
            echo "docs_coverage_passed=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: 🎨 Generate SonarCloud custom metrics
        id: generate-metrics
        run: |
          # Calculate overall documentation coverage (weighted average)
          DOC_COVERAGE="${{ steps.docs-coverage.outputs.doc_coverage }}"
          DOCSTRING_COVERAGE="${{ steps.interrogate.outputs.docstring_coverage }}"
          OVERALL_COVERAGE=$(python -c "print(int(($DOC_COVERAGE * 0.6) + ($DOCSTRING_COVERAGE * 0.4)))")

          echo "overall_coverage=${OVERALL_COVERAGE}" >> $GITHUB_OUTPUT

          # Create SonarCloud generic test execution report for documentation coverage
          mkdir -p coverage
          cat > coverage/documentation-coverage.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <testExecutions version="1">
            <file path="src/documentation-coverage.ts">
              <testCase name="Documentation Files Coverage" duration="1">
                <coverage>
                  <lineToCover lineNumber="1" covered="$([ $DOC_COVERAGE -ge 85 ] && echo "true" || echo "false")"/>
                </coverage>
              </testCase>
              <testCase name="Python Docstring Coverage" duration="1">
                <coverage>
                  <lineToCover lineNumber="2" covered="$([ $DOCSTRING_COVERAGE -ge 85 ] && echo "true" || echo "false")"/>
                </coverage>
              </testCase>
              <testCase name="Overall Documentation Coverage" duration="1">
                <coverage>
                  <lineToCover lineNumber="3" covered="$([ $OVERALL_COVERAGE -ge 85 ] && echo "true" || echo "false")"/>
                </coverage>
              </testCase>
            </file>
          </testExecutions>
          EOF

          # Create custom properties for SonarCloud
          cat > coverage/sonar-documentation.properties << EOF
          sonar.custom.documentation.files.coverage=${DOC_COVERAGE}
          sonar.custom.documentation.docstring.coverage=${DOCSTRING_COVERAGE}  
          sonar.custom.documentation.overall.coverage=${OVERALL_COVERAGE}
          EOF

      - name: 💬 Comment on PR with documentation results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const interrogatePassed = '${{ steps.interrogate.outputs.interrogate_passed }}' === 'true';
            const docsCoveragePassed = '${{ steps.docs-coverage.outputs.docs_coverage_passed }}' === 'true';
            const overallCoverage = '${{ steps.generate-metrics.outputs.overall_coverage }}';
            const docCoverage = '${{ steps.docs-coverage.outputs.doc_coverage }}';
            const docstringCoverage = '${{ steps.interrogate.outputs.docstring_coverage }}';

            const overallStatus = interrogatePassed && docsCoveragePassed ? '✅' : '❌';

            let comment = `## ${overallStatus} Documentation Coverage Report\n\n`;
            comment += `| Check | Status | Coverage |\n`;
            comment += `|-------|--------|---------|\n`;
            comment += `| Python Docstrings | ${interrogatePassed ? '✅' : '❌'} | ${docstringCoverage}% |\n`;
            comment += `| Documentation Files | ${docsCoveragePassed ? '✅' : '❌'} | ${docCoverage}% |\n`;
            comment += `| **Overall** | ${overallStatus} | **${overallCoverage}%** |\n\n`;
            comment += `*Coverage data will be available in SonarCloud dashboard*\n\n`;
            comment += `---\n*This comment was automatically generated by the Test Suite workflow.*`;

            // Find existing documentation coverage comment
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const existingComment = comments.find(comment => 
              comment.body.includes('Documentation Coverage Report')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }

      - name: Upload documentation coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation-coverage
          path: |
            coverage/documentation-coverage.xml
            coverage/sonar-documentation.properties
            interrogate_output.txt
          retention-days: 30

  # Status reporting jobs that consolidate matrix results
  playwright-status:
    name: Playwright Status
    needs: playwright-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report Playwright Status
        uses: actions/github-script@v7
        with:
          script: |
            const jobs = ${{ toJson(needs.playwright-tests.result) }};
            const success = jobs === 'success';
            const skipped = jobs === 'skipped';

            console.log(`Playwright tests result: ${jobs}`);

            if (skipped) {
              console.log('✅ Playwright tests were skipped');
            } else if (success) {
              console.log('✅ All Playwright tests passed');
            } else {
              console.log('❌ Some Playwright tests failed (non-blocking)');
            }

  jest-status:
    name: Jest Status
    needs: jest-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report Jest Status
        uses: actions/github-script@v7
        with:
          script: |
            const jobs = ${{ toJson(needs.jest-tests.result) }};
            const success = jobs === 'success';

            console.log(`Jest tests result: ${jobs}`);

            if (success) {
              console.log('✅ All Jest tests passed');
            } else {
              console.log('❌ Jest tests failed');
              process.exit(1);
            }

  # Final status job
  tests-complete:
    name: Tests Complete
    needs: [jest-status, playwright-status, documentation-coverage]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report Final Status
        run: |
          echo "🧪 Test Suite Complete"
          echo "======================"
          echo "Jest: ${{ needs.jest-status.result }}"
          echo "Playwright: ${{ needs.playwright-status.result }}"
          echo "Documentation: ${{ needs.documentation-coverage.result }}"

          if [[ "${{ needs.jest-status.result }}" == "success" ]]; then
            echo "✅ All required tests passed"
            if [[ "${{ needs.documentation-coverage.result }}" == "success" ]]; then
              echo "✅ Documentation coverage meets requirements"
            else
              echo "⚠️ Documentation coverage needs attention (non-blocking)"
            fi
          else
            echo "❌ Required tests failed"
            exit 1
          fi
