name: Release

on:
  push:
    branches:
      - master # or 'main' if that's your default branch name

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # Add this step to install release-it and its plugin
      - name: Install release-it and plugins
        run: npm install --save-dev release-it @release-it/conventional-changelog --legacy-peer-deps

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Clean working directory
        run: |
          git stash -u
          git clean -fdx

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx release-it --ci
