name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - master # or 'main' if that's your default branch name

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # Add this step to install release-it and its plugin
      - name: Install release-it and plugins
        run: npm install --save-dev release-it @release-it/conventional-changelog --legacy-peer-deps

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Clean working directory
        run: |
          git checkout -- .
          git clean -fdx -e node_modules

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: npm run release -- --ci
