name: Release

on:
  push:
    branches:
      - master # or 'main' if that's your default branch name

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # Add this step to install release-it and its plugin
      - name: Install release-it and plugins
        run: npm install --save-dev release-it @release-it/conventional-changelog --legacy-peer-deps

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Clean working directory
        run: |
          git checkout -- .
          git clean -fdx -e node_modules

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release -- --ci --dry-run
          git checkout -b release-${GITHUB_SHA::8}
          git push origin release-${GITHUB_SHA::8}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: release new version'
          title: 'Release new version'
          body: "This PR was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\nPlease review and merge to release a new version."
          branch: release-${GITHUB_SHA::8}
          base: master
